# when to run CI
on: [push, pull_request]

jobs:
  build:
    # what OS to run this on
    runs-on: ubuntu-latest

    # what steps will CI do 
    steps:
      # tells github to checkout our repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # installs things in order to run java
      - name: Install Compiler
        uses: actions/setup-java
        with:
          distribution: temurin
          java-version: 17

      # install make (usually already installed)
      - name: Install Make
        run: sudo apt-get install -y make

      # build java
      - name: Build
        run: make all

      # run java
      - name: Running Code
        run: make run
      
